// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukUnLefnjNANJJ61jcKC1gQJFi4WrUDo',
    appId: '1:31590109723:web:4af762115b400056ab1ebe',
    messagingSenderId: '31590109723',
    projectId: 'algeria-tour-de9d8',
    authDomain: 'algeria-tour-de9d8.firebaseapp.com',
    storageBucket: 'algeria-tour-de9d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oDJJzAN2cuQ1gidKfvyEcgZqQuJRwXY',
    appId: '1:31590109723:android:f1763a4ec49f4429ab1ebe',
    messagingSenderId: '31590109723',
    projectId: 'algeria-tour-de9d8',
    storageBucket: 'algeria-tour-de9d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDzMIGPjxPLXy1B2Slp4iH-cQcfRFhESE',
    appId: '1:31590109723:ios:019f35c4d2167088ab1ebe',
    messagingSenderId: '31590109723',
    projectId: 'algeria-tour-de9d8',
    storageBucket: 'algeria-tour-de9d8.appspot.com',
    iosBundleId: 'com.example.algerianTouristicGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDzMIGPjxPLXy1B2Slp4iH-cQcfRFhESE',
    appId: '1:31590109723:ios:a1a86314ff967a0eab1ebe',
    messagingSenderId: '31590109723',
    projectId: 'algeria-tour-de9d8',
    storageBucket: 'algeria-tour-de9d8.appspot.com',
    iosBundleId: 'com.example.algerianTouristicGuideApp.RunnerTests',
  );
}
